### ISSUE TITLE
Create the Domain Interface class

### ISSUE THREAD

**Issue by florianika** [parstat/structural-metadata#1]
Investigate the possibility to use Code First approach for Neo4j

https://www.thecodebuzz.com/crud-neo4j-csharp-asp-net-core-graph-database/

Define the Domain/Entity interface containing those properties:
(IdentifiableArtefact GSIM object)
1. ID (Long)
2. LocalID (String)
3. Name (Multilanguage String)
4. Description (Multilanguage String)
5. Version (Multilanguage String)
6. VersionDate (Date)
7. VersionRationale (Multilanguage String)

Multilanguage String: Property type that should be able to contain text in different languages.

**Comment by vchirilov** [comment]
**Neo4j database**

I looked into dedicated articles for neo4j and definitely it is something interesting.

Yes, it is possible to build up the system using graph db as neo4j, however there are some cons I would like to mention:

1. It is a new type of db that completely differ from ordinary databases (relational and no-sql) which will add more uncertainty in terms of development and it can affect delivery time.

2. I don't think neo4j would add more advantages compared to no-sql databases like MongoDB, Kafka

3. I would prefer to go with a no-sql database. I think no-sql suits our needs the best

4. The most popular no-sql is MongoDB (and I have some experience with it). There is already docker image for mongo (https://hub.docker.com/_/mongo).

**Multilanguage support**

I think we need to keep one column of type string which support UNICODE but de facto information in different languages will be kept and saved into database. Information in one or another language will be returned depending on an input parameter.
