### ISSUE TITLE
Create the IConcept interface that extends the IIdentifiableArtefact interface

### ISSUE THREAD

**Issue by florianika** [parstat/structural-metadata#2]
The IConcept (GSIM: Concept) interface is the interface that extends IIdentifiableArtefact (Identifiable Artefact GSIM)
Properties:
1. extends IIdentifiableArtefact
2. Definition (Multilanguage String)
This interface should be found on Presentation.Common.Domain under StructuralMetadata/Interfaces/Gsim/Concept folder

**Comment by vchirilov** [comment]
I believe Domain is more suitable to be an abstract class as well. I have changed Domain from an interface to an abstract class and extended Concept from Domain.

**Comment by florianika** [comment]
Please put IConcept and IUnitType under StructuralMetadat/Interfaces/Gsim/Concept folder

**Comment by vchirilov** [comment]
Changes have been made

Commit: 101fe363a8821a370f37bb6985639cc180905ff1 [101fe36]
Parents: a9d1774f00
Author: Veaceslav Chirilov <slavicchirilov@yahoo.com>
Date: Friday, July 2, 2021 12:48:00 PM
Committer: Veaceslav Chirilov

**Comment by florianika** [comment]
Please remove all unused references from each class
