### ISSUE TITLE
Create a value domain

### ISSUE THREAD

**Issue by florianika** [parstat/structural-metadata#20]
API method to create a value domain.

- [x] In the /Application/ValueDomains/Commands add CreateValueDomainCommand with this field:
1. string LocalId required
2. string Name required
3. string Description 
4. ValueDomainType Type (Enumarated, Described)
5. ValueDomainScope Scope (Sentinel, Substantive)
6. string Expression required if Type == Described
7. DataType DataType
8. long MeasurementUnitId
9. long NodesetId required if Type == Enumerated and LevelId is null
10. long LevelId required if Type == Enumerated and NodesetId is null

- [x] In the handler validate the command, check existence of MeasurementUnit, Level, or Noteset accordingly. Then create the new ValueDomain and return the id of the newly created object.
- [x] In the ValueDomain Controller add the POST API Method to create the value domain by sending the command to the handler.

**Comment by Enooo** [comment]
Task done.
