### ISSUE TITLE
API method to create a representation

### ISSUE THREAD

**Issue by florianika** [parstat/structural-metadata#24]
- [x] Add a command under /RepresentedVariables/Command/CreateRepresentation (CreateRepresentationCommand)
- [x] Or add command under /Variables/Command/AddRepresentation (AddVariableRepresentationCommand)
- [x] Fields of the command should contain (VariableId required, LocalId required, Name required, Description optional)
- [x] Create the command handler that checks if the variable exists then creates the representation 
- [x] Create api method (PUT) in ClosedVariableController HttpPut( '/representations' ) and send the command to the above created handler.
- [x] Add two more filed (long SubstantiveValueDomainId required, long SentinelValueDomainId)
- [x] In logic check the existence of valuedomains

**Comment by Enooo** [comment]
All tasks are implemented as required.

**Comment by florianika** [comment]
Add two more fields in the command:
1. long SentinelValueDomainId
2. long SubstantiveValueDomainId required 
Change the application logic accordingly.

**Comment by Enooo** [comment]
Fields are added and validated accordingly
