### ISSUE TITLE
API method to edit a representation 

### ISSUE THREAD

**Issue by florianika** [parstat/structural-metadata#26]
- [x] Add a command under /RepresentedVariables/Command/UpdateRepresentation (UpdateRepresentationCommand)
- [x] Fields of the command should contain (RepresentationId of just Id, Name optional, Description optional, long SubstantiveValueDomainId optional, SentinelValueDomainId optional)
- [x] Create the command handler that checks if the representation exists then updates the representation, only for fields that are sent.
- [x]  Create API method (PUT) in ClosedRepresentedVariableController HttpPut(  ) and send the command to the above created handler.
- [x] Investigate the possibility to migrate the create representation api method in this controller using POST method

**Comment by Enooo** [comment]
Implementation finished
