### ISSUE TITLE
Create the UnitType (GSIM: UnitType) Domain/Entity Class

### ISSUE THREAD

**Issue by florianika** [parstat/structural-metadata#4]
Create the interface IUnitType that extends the IConcept interface in the Common library.
Create the UnitType object that implements IUnitType by extending AbstarctIdentifiableArtefact, this object should be placed in Presentation.Domain under StructuralMetadata/Gsim/Concept folders.

**Comment by florianika** [comment]
it was not finished

**Comment by vchirilov** [comment]
Concept class has been removed, thus description is not up to date, I think.

I have created in Presentation.Domain, class UnitType like below

`public class UnitType : AbstractIdentifiableArtefact, IUnitType
    {
        public string Definition { get; set; }
    }`

**Comment by florianika** [comment]
I have updated the description.
Please try to remove every unused reference from each class you create.

**Comment by vchirilov** [comment]
Changes have been made

Commit: 101fe363a8821a370f37bb6985639cc180905ff1 [101fe36]
Parents: a9d1774f00
Author: Veaceslav Chirilov <slavicchirilov@yahoo.com>
Date: Friday, July 2, 2021 12:48:00 PM
Committer: Veaceslav Chirilov

**Comment by florianika** [comment]
UnitType should be under StructuralMetadata/Gsim/Concept folder and please remove all unused references from each class @vchirilov
